# Generated by Django 4.0.1 on 2024-10-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/profile_imgs/idefault-profile.png', null=True, upload_to='profile_imgs'),
        ),
    ]
