# Generated by Django 4.0.1 on 2024-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carfeature_defaultequipment_pickupfeature_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='car_category'),
        ),
    ]
