# Generated by Django 4.0.1 on 2024-10-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_brand_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ImageField(null=True, upload_to='brand_of_car'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
