# Generated by Django 4.0.1 on 2024-10-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_car_brand_delete_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ImageField(blank=True, null=True, upload_to='brand_of_car'),
        ),
    ]
