# Generated by Django 4.0.1 on 2024-10-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
    ]
