# Generated by Django 4.0.1 on 2024-10-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_car_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
