# Generated by Django 4.0.1 on 2024-11-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_car_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pickupfeature'),
        ),
    ]
