# Generated by Django 4.0.1 on 2024-11-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_car_current_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
    ]
