# Generated by Django 4.0.1 on 2024-11-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_car_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pickupfeature'),
        ),
    ]
