# Generated by Django 4.0.1 on 2024-11-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_car_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='destination1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='api.pickupfeature'),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='destination2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='api.pickupfeature'),
        ),
    ]
