# Generated by Django 4.0.1 on 2024-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_carbooking_destination1_carbooking_destination2'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='email_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='is_addon_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='is_addon_2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='is_addon_3',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='postcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='region_department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='street_number_and_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
