# Generated by Django 4.0.1 on 2024-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_carbooking_company_name_carbooking_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
