# Generated by Django 4.0.1 on 2024-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_carbooking_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
