# Generated by Django 4.0.1 on 2024-11-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
