# Generated by Django 4.0.1 on 2024-11-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='latest_offers')),
                ('description', models.CharField(max_length=150)),
                ('price_per_day', models.CharField(max_length=50)),
            ],
        ),
    ]
