# Generated by Django 4.0.1 on 2024-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_latestoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestoffers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
