# Generated by Django 4.0.1 on 2024-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
