# Generated by Django 4.0.1 on 2024-11-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestoffers',
            options={'verbose_name_plural': 'Offers'},
        ),
    ]
